name: Multi-platform build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: clang
            artifact_name: shiny-finder-linux
            binary_path: build/shiny-finder
          - os: windows-latest
            compiler: msys2-clang
            artifact_name: shiny-finder-windows
            binary_path: build/shiny-finder.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Linux Setup ---
      - name: Setup Linux Clang
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build

      # --- MSYS2 Windows Setup
      - name: Setup MSYS2
        if: ${{ matrix.os == 'windows-latest' }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          cache: true
          install: >-
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-ninja
            mingw-w64-clang-x86_64-toolchain

      # --- Build Step (Windows) ---
      - name: Build Windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: msys2 {0}
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      # --- Build Step (Linux) ---
      - name: Build Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.binary_path }}
          if-no-files-found: error